from __future__ import annotations

from datetime import datetime
from typing import Protocol

from vai_hold.domain.models import (
    ActionAttempt,
    ActionCommand,
    DiscoveryCursor,
    HoldBinding,
    HoldOrder,
    InboundEvent,
    Incident,
    ObservationSnapshot,
    OrderKey,
    OrderWafer,
    OutboxRow,
    SystemControl,
)


class HoldOrderDao(Protocol):
    def get(self, order_id: str) -> HoldOrder | None: ...
    def get_by_key(self, key: OrderKey) -> HoldOrder | None: ...
    def insert(self, order: HoldOrder) -> None: ...
    def update(self, order: HoldOrder, expected_version: int) -> None: ...
    def list_open(self, limit: int = 500) -> list[HoldOrder]: ...
    def list_all(self, limit: int = 2000) -> list[HoldOrder]: ...
    def try_claim(
        self,
        order_id: str,
        worker_id: str,
        until: datetime,
        expected_version: int,
        now: datetime | None = None,
    ) -> bool: ...
    def release_claim(self, order_id: str, worker_id: str) -> None: ...


class OrderWaferDao(Protocol):
    def replace_roster(self, order_id: str, roster_version: int, wafers: list[OrderWafer]) -> None: ...
    def list_by_order(self, order_id: str) -> list[OrderWafer]: ...
    def upsert_ai_result(self, row: OrderWafer) -> None: ...


class HoldBindingDao(Protocol):
    def add(self, binding: HoldBinding) -> None: ...
    def update(self, binding: HoldBinding) -> None: ...
    def list_by_order(self, order_id: str) -> list[HoldBinding]: ...
    def find_by_mes_tuple(
        self, lot_id: str, route_id: str, ope_no: str, hold_code: str, hold_user: str
    ) -> list[HoldBinding]: ...
    def list_all(self) -> list[HoldBinding]: ...


class ActionJournalDao(Protocol):
    def get_command(self, command_id: str) -> ActionCommand | None: ...
    def get_in_flight(self, order_id: str) -> ActionCommand | None: ...
    def list_by_order(self, order_id: str) -> list[ActionCommand]: ...
    def insert_prepared(self, command: ActionCommand) -> None: ...
    def save_command(self, command: ActionCommand) -> None: ...
    def add_attempt(self, attempt: ActionAttempt) -> None: ...
    def list_history(self, order_id: str) -> list[ActionAttempt]: ...


class IncidentDao(Protocol):
    def open_or_touch(self, incident: Incident) -> Incident: ...
    def get_open(self, subject_key: str, incident_type: str) -> Incident | None: ...
    def list_open(self, limit: int = 500) -> list[Incident]: ...
    def resolve(self, incident_id: str, actor: str, at: datetime) -> None: ...


class AlarmOutboxDao(Protocol):
    def enqueue(self, row: OutboxRow) -> None: ...
    def list_pending(self, now: datetime, limit: int = 100) -> list[OutboxRow]: ...
    def mark_sent(self, outbox_id: str, at: datetime, provider_msg_id: str | None) -> None: ...
    def mark_failed(self, outbox_id: str, at: datetime, error: str, next_retry_at: datetime) -> None: ...
    def mark_acked(self, outbox_id: str, at: datetime) -> None: ...
    def get(self, outbox_id: str) -> OutboxRow | None: ...


class SystemControlDao(Protocol):
    def get(self, scope: str) -> SystemControl: ...
    def save(self, control: SystemControl, expected_version: int) -> None: ...


class SnapshotDao(Protocol):
    def put(self, snap: ObservationSnapshot) -> None: ...
    def get(self, snapshot_id: str) -> ObservationSnapshot | None: ...


class DiscoveryCursorDao(Protocol):
    def get(self, name: str) -> DiscoveryCursor | None: ...
    def advance(self, name: str, last_event_id: str, last_event_time: datetime, at: datetime) -> None: ...


class InboundEventDao(Protocol):
    def try_record(self, event: InboundEvent) -> bool: ...
    def list_unconsumed(self, limit: int = 500) -> list[InboundEvent]: ...
    def mark_consumed(self, source_event_id: str, order_id: str | None) -> None: ...
    def get(self, source_event_id: str) -> InboundEvent | None: ...


class UnitOfWork(Protocol):
    orders: HoldOrderDao
    wafers: OrderWaferDao
    holds: HoldBindingDao
    actions: ActionJournalDao
    incidents: IncidentDao
    outbox: AlarmOutboxDao
    control: SystemControlDao
    snapshots: SnapshotDao
    cursors: DiscoveryCursorDao
    inbound: InboundEventDao

    def __enter__(self) -> UnitOfWork: ...
    def __exit__(self, exc_type, exc, tb) -> None: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...


class UnitOfWorkFactory(Protocol):
    def new(self) -> UnitOfWork: ...
