from __future__ import annotations

from typing import Protocol

from vai_hold.domain.scenario import ScenarioCase, ScenarioRunResult


class ScenarioCatalogDao(Protocol):
    """Fixture catalog. Not the production HoldOrder DAO."""

    def list_enabled(self) -> list[ScenarioCase]: ...
    def list_all(self) -> list[ScenarioCase]: ...
    def get(self, scenario_id: str) -> ScenarioCase | None: ...
    def upsert(self, case: ScenarioCase) -> None: ...
    def record_run(self, result: ScenarioRunResult) -> None: ...
    def count(self) -> int: ...
