"""Expected log/rule traces for T01-T38 investigation drills. Source: V1 §13."""

# rule_id values that MUST appear somewhere in the case log (or last_rule_id)
EXPECT = {
    "T01": {"rules": {"A1-03", "A2-02", "A2-11"}, "events": {"hold.intent", "hold.sent", "hold.receipt", "hold.confirmed", "release.confirmed"}},
    "T02": {"rules": {"A1-04", "A2-02"}, "events": {"hold.receipt"}},
    "T03": {"rules": {"A2-03"}, "events": {"hold.failed", "incident.opened"}},
    "T04": {"rules": {"A2-02"}, "events": {"hold.confirmed"}},
    "T05": {"rules": {"A2-14"}, "events": {"hold.verify_unknown"}},
    "T06": {"rules": {"A2-02"}, "events": {"hold.confirmed"}},
    "T07": {"rules": {"A1-01", "A1-03"}, "events": {"order.created"}},
    "T08": {"rules": {"A1-03"}, "events": {"hold.receipt"}},
    "T09": {"rules": {"A2-05"}, "events": {"decision.applied"}},
    "T10": {"rules": {"A2-05"}, "events": {"decision.applied"}},
    "T11": {"rules": {"A2-05"}, "events": {"decision.applied"}},
    "T12": {"rules": {"A2-07"}, "events": {"release.sent"}},
    "T13": {"rules": {"A1-03"}, "events": {"order.created"}},
    "T14": {"rules": {"A2-08", "A2-11"}, "events": {"release.confirmed"}},
    "T15": {"rules": {"A2-21"}, "events": {"release.sent"}},
    "T16": {"rules": {"A2-11"}, "events": {"release.confirmed"}},
    "T17": {"rules": {"A2-12"}, "events": {"release.failed"}},
    "T18": {"rules": {"A1-03"}, "events": {"decision.applied", "hold.sent"}},
    "T19": {"rules": {"A2-04"}, "events": {"decision.applied"}},
    "T20": {"rules": {"A2-13"}, "events": {"order.manual_closed"}},
    "T21": {"rules": set(), "events": {"decision.applied"}},
    "T22": {"rules": set(), "events": {"decision.applied"}},
    "T23": {"rules": set(), "events": {"decision.applied"}},
    "T24": {"rules": {"A2-02"}, "events": {"hold.confirmed"}},
    "T25": {"rules": {"A2-14"}, "events": {"decision.applied"}},
    "T26": {"rules": {"D-01"}, "events": {"incident.opened"}},
    "T27": {"rules": {"D-02"}, "events": {"control.disabled"}},
    "T28": {"rules": {"A1-08"}, "events": {"decision.applied"}},
    "T29": {"rules": {"D-03"}, "events": {"incident.opened"}},
    "T30": {"rules": {"D-04"}, "events": {"hold.orphan"}},
    "T31": {"rules": {"D-05"}, "events": {"incident.opened"}},
    "T32": {"rules": {"A2-03"}, "events": {"notify.sent"}},
    "T33": {"rules": set(), "events": set()},
    "T34": {"rules": {"A1-08"}, "events": {"control.resume_denied"}},
    "T35": {"rules": {"D-06"}, "events": {"agent.stall"}},
    "T36": {"rules": {"A2-05"}, "events": {"roster.changed"}},
    "T37": {"rules": {"A2-14"}, "events": {"observation.stale"}},
    "T38": {"rules": {"A2-03"}, "events": {"hold.failed"}},
}
