"""Stable log event IDs. Do not rename without updating Design/LOG_CODE_MAP.md."""


class Event:
    PIPELINE_START = "pipeline.start"
    PIPELINE_END = "pipeline.end"
    EVAL = "eval.cycle"
    ORDER_CREATED = "order.created"
    ORDER_SKIP_CLAIM = "order.skip_claim"
    SCOPE_SKIP_LOT = "scope.skip_lot"
    DECISION = "decision.applied"
    HOLD_INTENT = "hold.intent"
    HOLD_SENT = "hold.sent"
    HOLD_RECEIPT = "hold.receipt"
    HOLD_CONFIRMED = "hold.confirmed"
    HOLD_VERIFY_UNKNOWN = "hold.verify_unknown"
    HOLD_FAILED = "hold.failed"
    RELEASE_INTENT = "release.intent"
    RELEASE_SENT = "release.sent"
    RELEASE_RECEIPT = "release.receipt"
    RELEASE_CONFIRMED = "release.confirmed"
    RELEASE_NOT_UNIQUE = "release.not_unique"
    RELEASE_FAILED = "release.failed"
    TRANSFER_INTENT = "transfer.intent"
    TRANSFER_SENT = "transfer.sent"
    TRANSFER_RECEIPT = "transfer.receipt"
    TRANSFER_CONFIRMED = "transfer.confirmed"
    TRANSFER_FAILED = "transfer.failed"
    INCIDENT_OPENED = "incident.opened"
    NOTIFY_SENT = "notify.sent"
    NOTIFY_FAILED = "notify.failed"
    CONTROL_DISABLED = "control.disabled"
    CONTROL_RESUME = "control.resume"
    CONTROL_RESUME_DENIED = "control.resume_denied"
    MANUAL_CLOSED = "order.manual_closed"
    DISCOVERY_IDENTITY = "discovery.identity_unknown"
    ORPHAN_HOLD = "hold.orphan"
    AGENT_STALL = "agent.stall"
    ROSTER_CHANGED = "roster.changed"
    STALE_EVENT = "observation.stale"
