from __future__ import annotations

from enum import StrEnum


class FunctionCode(StrEnum):
    SET_DEFAULT_HOLD = "SET_DEFAULT_HOLD_BY_Operation_Start"
    CONFIRM_HOLD = "CONFIRM_DEFAULT_HOLD_EXISTS"
    CHECK_AI = "CHECK_AI_SCAN_COMPLETE"
    CONFIRM_RELEASE = "CONFIRM_DEFAULT_HOLD_RELEASED"
    DEFENSE = "SMM_EXCEPTION_DEFENSE"
    RESUME = "VAI_RESUME"
    MANUAL_CLOSE = "VAI_MANUAL_CLOSE"


class Lifecycle(StrEnum):
    OPEN = "OPEN"
    CLOSED = "CLOSED"
    MANUAL_CLOSED = "MANUAL_CLOSED"


class ProtectionState(StrEnum):
    NONE = "NONE"
    SET_PENDING = "SET_PENDING"
    CONFIRMED = "CONFIRMED"
    UNKNOWN = "UNKNOWN"
    FAILED = "FAILED"
    LOST = "LOST"
    RELEASE_PENDING = "RELEASE_PENDING"
    RELEASED = "RELEASED"


class AiState(StrEnum):
    UNKNOWN = "UNKNOWN"
    WAITING = "WAITING"
    COMPLETE_OK = "COMPLETE_OK"
    COMPLETE_DEFECT = "COMPLETE_DEFECT"
    INVALID = "INVALID"


class WorkState(StrEnum):
    NEED_ORDER = "NEED_ORDER"
    NEED_TARGET = "NEED_TARGET"
    NEED_HOLD = "NEED_HOLD"
    NEED_BACKUP_HOLD = "NEED_BACKUP_HOLD"
    HOLD_VERIFY_PENDING = "HOLD_VERIFY_PENDING"
    PROTECTION_CONFIRMED = "PROTECTION_CONFIRMED"
    WAIT_AI = "WAIT_AI"
    AI_RESULT_INVALID = "AI_RESULT_INVALID"  # 舊 DB／log 相容；目前不產生
    READY_RELEASE_OK = "READY_RELEASE_OK"
    READY_RELEASE_HANDOFF = "READY_RELEASE_HANDOFF"  # 舊 DB／log 相容；目前不產生
    DEFECT_HOLD_UNCONFIRMED = "DEFECT_HOLD_UNCONFIRMED"  # 舊 DB／log 相容；目前不產生
    RELEASE_SENT = "RELEASE_SENT"
    RELEASE_VERIFY_PENDING = "RELEASE_VERIFY_PENDING"
    RELEASE_FAILED = "RELEASE_FAILED"
    HOLD_FAILED = "HOLD_FAILED"
    HOLD_MISSING = "HOLD_MISSING"
    CLOSED = "CLOSED"
    MANUAL_CLOSED = "MANUAL_CLOSED"
    BLOCKED_BY_CONTROL = "BLOCKED_BY_CONTROL"
    OBSERVATION_UNKNOWN = "OBSERVATION_UNKNOWN"
    MANUAL_REVIEW = "MANUAL_REVIEW"
    STATE_CONFLICT = "STATE_CONFLICT"
    NONE = "NONE"


class SourceStatus(StrEnum):
    FOUND = "FOUND"
    NOT_FOUND = "NOT_FOUND"
    UNKNOWN = "UNKNOWN"
    STALE = "STALE"


class ReceiptOutcome(StrEnum):
    NOT_SENT = "NOT_SENT"
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"
    UNKNOWN = "UNKNOWN"


class ActionState(StrEnum):
    PREPARED = "PREPARED"
    DISPATCHED = "DISPATCHED"
    ACKNOWLEDGED = "ACKNOWLEDGED"
    REJECTED = "REJECTED"
    UNKNOWN = "UNKNOWN"
    CONFIRMED = "CONFIRMED"
    CANCELLED = "CANCELLED"
    RETRY_WAIT = "RETRY_WAIT"


class ActionType(StrEnum):
    CREATE_ORDER = "CREATE_ORDER"
    SET_HOLD = "SET_HOLD"
    VERIFY_HOLD = "VERIFY_HOLD"
    SET_RELEASE = "SET_RELEASE"
    VERIFY_RELEASE = "VERIFY_RELEASE"
    # 只為讀取舊 Order DB／log 保留；目前程式沒有 transfer writer。
    TRANSFER_HOLD = "TRANSFER_HOLD"
    RAISE_ALARM = "RAISE_ALARM"
    DISABLE_NEW_HOLDS = "DISABLE_NEW_HOLDS"
    APPROVE_RESUME = "APPROVE_RESUME"


class BindingRole(StrEnum):
    PREVENTIVE = "PREVENTIVE"
    DEFECT_REFERENCE = "DEFECT_REFERENCE"


class BindingStatus(StrEnum):
    PENDING = "PENDING"
    CONFIRMED = "CONFIRMED"
    ACTIVE = "ACTIVE"
    RELEASE_PENDING = "RELEASE_PENDING"
    RELEASED = "RELEASED"
    LOST = "LOST"
    FAILED = "FAILED"


class HoldKind(StrEnum):
    FUTURE = "FUTURE"
    CURRENT = "CURRENT"


class ControlMode(StrEnum):
    ENABLED = "ENABLED"
    DISABLED_NEW_HOLD = "DISABLED_NEW_HOLD"
    RECOVERY_PENDING = "RECOVERY_PENDING"


class ManualControl(StrEnum):
    NONE = "NONE"
    TAKEOVER = "TAKEOVER"
    BLOCKED = "BLOCKED"


class BusinessAction(StrEnum):
    CREATE_ORDER = "CREATE_ORDER"
    SELECT_TARGET = "SELECT_TARGET"
    SET_HOLD = "SET_HOLD"
    VERIFY_HOLD = "VERIFY_HOLD"
    CHECK_AI = "CHECK_AI"
    SET_RELEASE = "SET_RELEASE"
    VERIFY_RELEASE = "VERIFY_RELEASE"
    # 相容舊資料；derive_state 不會產生此 action。
    TRANSFER_HOLD = "TRANSFER_HOLD"
    OPEN_INCIDENT = "OPEN_INCIDENT"
    NONE = "NONE"
